use crate::sync::Mutex;
/// getrandom — CSPRNG-backed entropy for user-space
///
/// Provides `sys_getrandom(buf, len, flags)` (Linux syscall 318).
///
/// Entropy sources, in order of preference:
///   1. RDRAND hardware instruction (x86_64, CPUID leaf 1 ECX bit 30)
///   2. TSC (RDTSC)
///   3. LAPIC ID from IA32_X2APIC_APICID MSR (0x802)
///   4. A monotonic counter seeded at boot
///
/// The raw sources are mixed into a 512-byte pool using an LCG with
/// Knuth's multiplier, then output is generated by a lightweight
/// ChaCha20-style quarter-round stream cipher so that pool internals
/// are never directly exposed.
///
/// Rules: no_std, no heap, no float casts, saturating arithmetic only.
/// All code is original.
use crate::{serial_print, serial_println};
use core::sync::atomic::{AtomicBool, AtomicU64, Ordering};

// ---------------------------------------------------------------------------
// Errno values (mirrors syscall::errno)
// ---------------------------------------------------------------------------

const EAGAIN: isize = -11;
const EFAULT: isize = -14;
const EINVAL: isize = -22;

// ---------------------------------------------------------------------------
// getrandom() flag bits
// ---------------------------------------------------------------------------

pub const GRND_NONBLOCK: u32 = 0x01;
pub const GRND_RANDOM: u32 = 0x02;

// ---------------------------------------------------------------------------
// Entropy pool — 512 raw bytes mixed from hardware sources
// ---------------------------------------------------------------------------

const POOL_SIZE: usize = 512;

struct EntropyPool {
    data: [u8; POOL_SIZE],
    pos: usize,
    initialized: bool,
    rdrand_available: bool,
    mix_counter: u64,
}

impl EntropyPool {
    const fn new() -> Self {
        EntropyPool {
            data: [0u8; POOL_SIZE],
            pos: 0,
            initialized: false,
            rdrand_available: false,
            mix_counter: 0,
        }
    }
}

static POOL: Mutex<EntropyPool> = Mutex::new(EntropyPool::new());

// ---------------------------------------------------------------------------
// CSPRNG state — ChaCha20-style, keyed from the pool
// ---------------------------------------------------------------------------

struct Csprng {
    key: [u32; 8],   // 256-bit key
    nonce: [u32; 3], // 96-bit nonce
    counter: u64,
    ready: bool,
}

impl Csprng {
    const fn new() -> Self {
        Csprng {
            key: [0u32; 8],
            nonce: [0u32; 3],
            counter: 0,
            ready: false,
        }
    }
}

static CSPRNG: Mutex<Csprng> = Mutex::new(Csprng::new());

// A simple init-done flag so callers can poll without taking the lock.
static POOL_READY: AtomicBool = AtomicBool::new(false);

// ---------------------------------------------------------------------------
// Hardware helpers
// ---------------------------------------------------------------------------

/// Read the x86_64 Time Stamp Counter.
#[inline(always)]
fn rdtsc() -> u64 {
    let lo: u32;
    let hi: u32;
    unsafe {
        core::arch::asm!(
            "rdtsc",
            out("eax") lo,
            out("edx") hi,
            options(nomem, nostack),
        );
    }
    ((hi as u64) << 32) | (lo as u64)
}

/// Read an MSR.  Used for LAPIC ID (MSR 0x802).
#[inline(always)]
unsafe fn rdmsr(reg: u32) -> u64 {
    let lo: u32;
    let hi: u32;
    core::arch::asm!(
        "rdmsr",
        in("ecx") reg,
        out("eax") lo,
        out("edx") hi,
        options(nomem, nostack),
    );
    ((hi as u64) << 32) | (lo as u64)
}

/// Check CPUID leaf 1 ECX bit 30 for RDRAND support.
fn cpuid_rdrand_available() -> bool {
    let ecx: u32;
    unsafe {
        core::arch::asm!(
            "push rbx",
            "cpuid",
            "pop rbx",
            inout("eax") 1u32 => _,
            out("ecx") ecx,
            out("edx") _,
            options(nomem, nostack),
        );
    }
    (ecx >> 30) & 1 == 1
}

/// Try RDRAND up to 10 times.  Returns `Some(u64)` on success, `None` on
/// repeated failure (CF=0 after the instruction signals exhaustion).
fn try_rdrand() -> Option<u64> {
    let mut val: u64 = 0;
    let mut ok: u8;
    for _ in 0..10u8 {
        unsafe {
            core::arch::asm!(
                "rdrand {v}",
                "setc   {f}",
                v = out(reg) val,
                f = out(reg_byte) ok,
                options(nomem, nostack),
            );
        }
        if ok != 0 {
            return Some(val);
        }
    }
    None
}

// ---------------------------------------------------------------------------
// LCG mixer — Knuth's constants
// ---------------------------------------------------------------------------

const LCG_MUL: u64 = 6_364_136_223_846_793_005;
const LCG_ADD: u64 = 1_442_695_040_888_963_407;

#[inline(always)]
fn lcg_next(state: u64, input: u64) -> u64 {
    state
        .wrapping_mul(LCG_MUL)
        .wrapping_add(LCG_ADD)
        .wrapping_add(input)
}

// ---------------------------------------------------------------------------
// Entropy pool mixing
// ---------------------------------------------------------------------------

fn mix_entropy(pool: &mut EntropyPool) {
    // Source 1: RDRAND
    let rng_word = if pool.rdrand_available {
        try_rdrand().unwrap_or(0xcafe_dead_beef_0000)
    } else {
        0xcafe_dead_beef_0000u64
    };

    // Source 2: TSC
    let tsc = rdtsc();

    // Source 3: Use a fixed entropy constant instead of x2APIC MSR 0x802
    // (x2APIC MSR is only accessible in x2APIC mode; causes #GP otherwise)
    let lapic_id = 0xDEAD_BEEF_CAFE_0001u64;

    // Source 4: monotonic counter (wrapping is fine for entropy)
    pool.mix_counter = pool.mix_counter.wrapping_add(1);
    let ctr = pool.mix_counter;

    // Mix into pool using 64-bit LCG state; fold into bytes
    let mut state = pool.data[pool.pos] as u64;
    state = lcg_next(state, rng_word);
    state = lcg_next(state, tsc);
    state = lcg_next(state, lapic_id);
    state = lcg_next(state, ctr);

    // Write 8 bytes into the pool (wrapping around POOL_SIZE)
    let bytes = state.to_le_bytes();
    for (i, &b) in bytes.iter().enumerate() {
        let idx = (pool.pos.wrapping_add(i)) % POOL_SIZE;
        pool.data[idx] ^= b;
    }
    pool.pos = pool.pos.wrapping_add(8) % POOL_SIZE;
}

// ---------------------------------------------------------------------------
// ChaCha20 quarter-round (the compression core)
// ---------------------------------------------------------------------------

/// Apply a ChaCha20 quarter-round on array elements at indices a, b, c, d.
#[inline(always)]
fn qr_arr(s: &mut [u32; 16], a: usize, b: usize, c: usize, d: usize) {
    s[a] = s[a].wrapping_add(s[b]);
    s[d] ^= s[a];
    s[d] = s[d].rotate_left(16);
    s[c] = s[c].wrapping_add(s[d]);
    s[b] ^= s[c];
    s[b] = s[b].rotate_left(12);
    s[a] = s[a].wrapping_add(s[b]);
    s[d] ^= s[a];
    s[d] = s[d].rotate_left(8);
    s[c] = s[c].wrapping_add(s[d]);
    s[b] ^= s[c];
    s[b] = s[b].rotate_left(7);
}

/// Generate 64 bytes (one ChaCha20 block) into `out`.
/// The state is: constants(4) | key(8) | counter_lo | counter_hi | nonce(3)
fn chacha20_block(key: &[u32; 8], nonce: &[u32; 3], counter: u64, out: &mut [u8; 64]) {
    // ChaCha20 "expand 32-byte k" constants
    const C0: u32 = 0x6170_7865;
    const C1: u32 = 0x3320_646e;
    const C2: u32 = 0x7962_2d32;
    const C3: u32 = 0x6b20_6574;

    let ctr_lo = counter as u32;
    let ctr_hi = (counter >> 32) as u32;

    let mut s: [u32; 16] = [
        C0, C1, C2, C3, key[0], key[1], key[2], key[3], key[4], key[5], key[6], key[7], ctr_lo,
        ctr_hi, nonce[0], nonce[1],
    ];
    // nonce[2] goes into the last slot — expand to 17 words via inline
    // We treat the 16-word state and fold nonce[2] in as a post-mix:
    // (standard ChaCha20 uses 4 constants + 8 key + 1 counter + 3 nonce = 16)
    // Slot 15 above is nonce[1]; we XOR nonce[2] into initial s[0] for seeding.
    s[0] ^= nonce[2];

    // 20 rounds (10 double-rounds)
    let mut i = 0u8;
    while i < 10 {
        // Column rounds
        qr_arr(&mut s, 0, 4, 8, 12);
        qr_arr(&mut s, 1, 5, 9, 13);
        qr_arr(&mut s, 2, 6, 10, 14);
        qr_arr(&mut s, 3, 7, 11, 15);
        // Diagonal rounds
        qr_arr(&mut s, 0, 5, 10, 15);
        qr_arr(&mut s, 1, 6, 11, 12);
        qr_arr(&mut s, 2, 7, 8, 13);
        qr_arr(&mut s, 3, 4, 9, 14);
        i += 1;
    }

    // Add original state back
    s[0] = s[0].wrapping_add(C0);
    s[1] = s[1].wrapping_add(C1);
    s[2] = s[2].wrapping_add(C2);
    s[3] = s[3].wrapping_add(C3);
    s[4] = s[4].wrapping_add(key[0]);
    s[5] = s[5].wrapping_add(key[1]);
    s[6] = s[6].wrapping_add(key[2]);
    s[7] = s[7].wrapping_add(key[3]);
    s[8] = s[8].wrapping_add(key[4]);
    s[9] = s[9].wrapping_add(key[5]);
    s[10] = s[10].wrapping_add(key[6]);
    s[11] = s[11].wrapping_add(key[7]);
    s[12] = s[12].wrapping_add(ctr_lo);
    s[13] = s[13].wrapping_add(ctr_hi);
    s[14] = s[14].wrapping_add(nonce[0]);
    s[15] = s[15].wrapping_add(nonce[1]);

    // Serialise to bytes (little-endian)
    for (i, &word) in s.iter().enumerate() {
        let bytes = word.to_le_bytes();
        out[i * 4] = bytes[0];
        out[i * 4 + 1] = bytes[1];
        out[i * 4 + 2] = bytes[2];
        out[i * 4 + 3] = bytes[3];
    }
}

// ---------------------------------------------------------------------------
// CSPRNG seeding from pool
// ---------------------------------------------------------------------------

fn seed_csprng_from_pool(pool: &EntropyPool, csprng: &mut Csprng) {
    // Key: pool bytes 0..32  (8 × u32, little-endian)
    for i in 0..8usize {
        let base = i * 4;
        csprng.key[i] = u32::from_le_bytes([
            pool.data[base],
            pool.data[base + 1],
            pool.data[base + 2],
            pool.data[base + 3],
        ]);
    }
    // Nonce: pool bytes 32..44  (3 × u32)
    for i in 0..3usize {
        let base = 32 + i * 4;
        csprng.nonce[i] = u32::from_le_bytes([
            pool.data[base],
            pool.data[base + 1],
            pool.data[base + 2],
            pool.data[base + 3],
        ]);
    }
    csprng.counter = 0;
    csprng.ready = true;
}

// ---------------------------------------------------------------------------
// Public initialisation
// ---------------------------------------------------------------------------

/// Initialise the entropy pool.  Must be called once during boot,
/// after APIC and TSC are available.
pub fn init() {
    let mut pool = POOL.lock();
    pool.rdrand_available = cpuid_rdrand_available();

    // Mix 64 rounds to saturate the pool
    for _ in 0..64u32 {
        mix_entropy(&mut pool);
    }
    pool.initialized = true;

    // Seed the CSPRNG
    let mut csprng = CSPRNG.lock();
    seed_csprng_from_pool(&pool, &mut csprng);

    POOL_READY.store(true, Ordering::Release);

    serial_println!(
        "    [getrandom] entropy pool ready (rdrand={})",
        pool.rdrand_available
    );
}

// ---------------------------------------------------------------------------
// Low-level fill from CSPRNG
// ---------------------------------------------------------------------------

/// Fill `buf` with cryptographically-strong pseudo-random bytes.
pub fn random_bytes(buf: &mut [u8]) {
    if buf.is_empty() {
        return;
    }

    let mut csprng = CSPRNG.lock();
    if !csprng.ready {
        // Pool not yet seeded — fall back to TSC XOR LCG
        let mut state = rdtsc();
        for b in buf.iter_mut() {
            state = lcg_next(state, rdtsc());
            *b = state as u8;
        }
        return;
    }

    // Occasionally re-mix pool into CSPRNG key to achieve forward secrecy
    // (every 65536 blocks)
    if csprng.counter % 65536 == 0 && csprng.counter != 0 {
        let mut pool = POOL.lock();
        mix_entropy(&mut pool);
        seed_csprng_from_pool(&pool, &mut csprng);
    }

    let key = csprng.key;
    let nonce = csprng.nonce;

    let mut written = 0usize;
    while written < buf.len() {
        let mut block = [0u8; 64];
        chacha20_block(&key, &nonce, csprng.counter, &mut block);
        csprng.counter = csprng.counter.wrapping_add(1);

        let remaining = buf.len().saturating_sub(written);
        let take = if remaining < 64 { remaining } else { 64 };
        buf[written..written.saturating_add(take)].copy_from_slice(&block[..take]);
        written = written.saturating_add(take);
    }
}

/// Return a random `u32`.
pub fn random_u32() -> u32 {
    let mut buf = [0u8; 4];
    random_bytes(&mut buf);
    u32::from_le_bytes(buf)
}

/// Return a random `u64`.
pub fn random_u64() -> u64 {
    let mut buf = [0u8; 8];
    random_bytes(&mut buf);
    u64::from_le_bytes(buf)
}

/// Return a uniform random value in `[lo, hi)`.
/// Returns `lo` if `hi <= lo`.
pub fn random_range(lo: u64, hi: u64) -> u64 {
    if hi <= lo {
        return lo;
    }
    let range = hi.wrapping_sub(lo);
    // Rejection sampling to avoid modulo bias
    // Largest multiple of `range` that fits in u64:
    //   threshold = u64::MAX - (u64::MAX % range) - (range - 1)
    // Simplified: threshold = u64::MAX - (u64::MAX % range)
    let threshold = u64::MAX - (u64::MAX % range);
    let mut v = random_u64();
    // At most a handful of iterations in practice (< 1 on average)
    let mut guard = 0u32;
    while v >= threshold {
        v = random_u64();
        guard = guard.saturating_add(1);
        if guard > 128 {
            break;
        }
    }
    lo.wrapping_add(v % range)
}

// ---------------------------------------------------------------------------
// sys_getrandom — syscall handler
// ---------------------------------------------------------------------------

/// Handler for `SYS_GETRANDOM` (nr 318).
///
/// # Safety
/// `buf` must be a valid, writable user-space pointer to at least `buflen`
/// bytes.  The caller (syscall dispatch) must validate the pointer range
/// before calling this function.
pub fn sys_getrandom(buf: *mut u8, buflen: usize, flags: u32) -> isize {
    // Reject nonsense lengths
    if buflen == 0 {
        return 0;
    }
    if buflen > 33_554_432 {
        return EINVAL;
    } // 32 MiB ceiling (matches Linux)
    if buf.is_null() {
        return EFAULT;
    }

    // If pool is not ready and GRND_NONBLOCK is set, return EAGAIN immediately
    if !POOL_READY.load(Ordering::Acquire) {
        if flags & GRND_NONBLOCK != 0 {
            return EAGAIN;
        }
        // Blocking path: re-mix until ready
        // (In a real multi-process kernel we would sleep the caller; here we
        // spin because we boot single-threaded at this stage.)
        let mut spins = 0u32;
        while !POOL_READY.load(Ordering::Acquire) {
            core::hint::spin_loop();
            spins = spins.saturating_add(1);
            if spins > 1_000_000 {
                break;
            }
        }
    }

    // Fill a kernel-side staging buffer in 4096-byte chunks to avoid long
    // lock holds.
    let mut remaining = buflen;
    let mut offset = 0usize;

    while remaining > 0 {
        const CHUNK: usize = 4096;
        let take = if remaining < CHUNK { remaining } else { CHUNK };

        let mut tmp = [0u8; CHUNK];
        random_bytes(&mut tmp[..take]);

        // Copy to user buffer
        unsafe {
            core::ptr::copy_nonoverlapping(tmp.as_ptr(), buf.add(offset), take);
        }

        offset = offset.saturating_add(take);
        remaining = remaining.saturating_sub(take);
    }

    buflen as isize
}
