use crate::sync::Mutex;
/// Adaptive behavior engine for Genesis learning subsystem
///
/// Uses learned patterns to proactively optimize the user experience:
///   - Preload predictions: anticipate which apps/resources to warm up
///   - Layout optimization: reorder UI elements by predicted relevance
///   - Auto-suggest: surface contextual suggestions without explicit query
///   - Resource scheduling: allocate CPU/memory based on predicted demand
///   - Habit reinforcement: nudge users toward productive routines
///
/// All math is Q16 fixed-point (i32, 16 fractional bits).
use alloc::vec::Vec;

use crate::{serial_print, serial_println};

// ── Q16 fixed-point ────────────────────────────────────────────────────────

const Q16_ONE: i32 = 65536;
const Q16_HALF: i32 = 32768;
const Q16_ZERO: i32 = 0;
const Q16_QUARTER: i32 = 16384; // 0.25
const Q16_TENTH: i32 = 6554; // 0.1
const Q16_THRESHOLD_LOW: i32 = 19661; // 0.3
const Q16_THRESHOLD_HIGH: i32 = 45875; // 0.7

fn q16_mul(a: i32, b: i32) -> i32 {
    (((a as i64) * (b as i64)) >> 16) as i32
}

fn q16_div(a: i32, b: i32) -> i32 {
    if b == 0 {
        return 0;
    }
    (((a as i64) << 16) / (b as i64)) as i32
}

/// Clamp a Q16 value to [0, Q16_ONE]
fn q16_clamp01(v: i32) -> i32 {
    if v < Q16_ZERO {
        Q16_ZERO
    } else if v > Q16_ONE {
        Q16_ONE
    } else {
        v
    }
}

// ── Configuration ──────────────────────────────────────────────────────────

const MAX_PRELOAD_SLOTS: usize = 8;
const MAX_LAYOUT_ITEMS: usize = 32;
const MAX_SUGGESTIONS: usize = 16;
const MAX_RESOURCE_HINTS: usize = 16;
const MAX_HABIT_NUDGES: usize = 8;

// ── Types ──────────────────────────────────────────────────────────────────

/// Priority level for preloading
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PreloadPriority {
    Critical, // very high confidence, preload immediately
    High,     // likely needed soon
    Medium,   // may be needed
    Low,      // speculative
}

/// A preload request generated by the adaptation engine
pub struct PreloadRequest {
    pub app_id: u16,
    pub priority: PreloadPriority,
    pub confidence: i32,       // Q16 [0..1]
    pub estimated_use_in: u64, // ticks until predicted use
    pub memory_hint_kb: u32,   // how much memory to reserve
    pub issued_at: u64,
    pub fulfilled: bool,
}

/// A layout slot with adaptive ordering
pub struct LayoutSlot {
    pub item_id: u16,
    pub base_position: u8,   // original position in layout
    pub adapted_score: i32,  // Q16 relevance score
    pub times_promoted: u32, // how many times moved higher
    pub times_demoted: u32,  // how many times moved lower
    pub locked: bool,        // user pinned this position
}

/// A contextual suggestion surfaced to the user
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SuggestionKind {
    LaunchApp,
    OpenFile,
    RunShortcut,
    AdjustSetting,
    ContactPerson,
    ScheduleReminder,
}

pub struct AdaptiveSuggestion {
    pub kind: SuggestionKind,
    pub target_id: u32,
    pub confidence: i32,  // Q16
    pub reason_code: u16, // why this was suggested
    pub shown: bool,
    pub accepted: bool,
    pub dismissed: bool,
    pub created_at: u64,
}

/// Resource allocation hint based on predicted workload
pub struct ResourceHint {
    pub app_id: u16,
    pub cpu_weight: i32,      // Q16 [0..1] relative CPU priority
    pub memory_priority: i32, // Q16 [0..1] how aggressively to keep in RAM
    pub io_priority: i32,     // Q16 [0..1] I/O scheduling weight
    pub valid_until: u64,     // tick at which this hint expires
}

/// A nudge toward a productive habit
pub struct HabitNudge {
    pub habit_id: u16,
    pub message_code: u16, // localized message identifier
    pub strength: i32,     // Q16 how strongly to nudge
    pub hour_trigger: u8,  // when to show
    pub day_mask: u8,      // which days (bit flags, Mon=bit0)
    pub times_shown: u32,
    pub times_followed: u32,
    pub active: bool,
}

/// The main adaptation engine
pub struct AdaptationEngine {
    pub enabled: bool,
    pub preload_queue: Vec<PreloadRequest>,
    pub layout_slots: Vec<LayoutSlot>,
    pub suggestions: Vec<AdaptiveSuggestion>,
    pub resource_hints: Vec<ResourceHint>,
    pub habit_nudges: Vec<HabitNudge>,
    pub current_tick: u64,
    pub preload_hit_count: u32,
    pub preload_miss_count: u32,
    pub suggestion_accept_rate: i32, // Q16 rolling acceptance rate
    pub adaptation_aggression: i32,  // Q16 how eagerly to adapt [0..1]
}

impl AdaptationEngine {
    const fn new() -> Self {
        AdaptationEngine {
            enabled: true,
            preload_queue: Vec::new(),
            layout_slots: Vec::new(),
            suggestions: Vec::new(),
            resource_hints: Vec::new(),
            habit_nudges: Vec::new(),
            current_tick: 0,
            preload_hit_count: 0,
            preload_miss_count: 0,
            suggestion_accept_rate: Q16_HALF,
            adaptation_aggression: Q16_HALF,
        }
    }

    /// Generate preload requests based on pattern predictions
    pub fn generate_preloads(
        &mut self,
        _current_app: u16,
        _hour: u8,
        _day: u8,
        predictions: &[(u16, i32)], // (app_id, confidence)
    ) {
        if !self.enabled {
            return;
        }

        // Clear expired / fulfilled preloads
        self.preload_queue
            .retain(|p| !p.fulfilled && p.issued_at + 60000 > self.current_tick);

        for &(app_id, confidence) in predictions {
            if confidence < Q16_THRESHOLD_LOW {
                continue;
            }
            if self.preload_queue.len() >= MAX_PRELOAD_SLOTS {
                break;
            }

            // Don't duplicate
            let already_queued = self.preload_queue.iter().any(|p| p.app_id == app_id);
            if already_queued {
                continue;
            }

            let priority = if confidence > Q16_THRESHOLD_HIGH {
                PreloadPriority::Critical
            } else if confidence > Q16_HALF {
                PreloadPriority::High
            } else if confidence > Q16_THRESHOLD_LOW {
                PreloadPriority::Medium
            } else {
                PreloadPriority::Low
            };

            // Estimate time until use: higher confidence = sooner
            let estimated_ticks = if confidence > Q16_THRESHOLD_HIGH {
                1000
            } else if confidence > Q16_HALF {
                5000
            } else {
                15000
            };

            // Memory hint: base 256KB, scale by confidence
            let mem_kb = (q16_mul(confidence, 256 * Q16_ONE / 1) >> 16) as u32;
            let mem_kb = if mem_kb < 64 { 64 } else { mem_kb };

            self.preload_queue.push(PreloadRequest {
                app_id,
                priority,
                confidence,
                estimated_use_in: estimated_ticks,
                memory_hint_kb: mem_kb,
                issued_at: self.current_tick,
                fulfilled: false,
            });
        }
    }

    /// Mark a preload as hit (the user actually launched the preloaded app)
    pub fn preload_hit(&mut self, app_id: u16) {
        for req in self.preload_queue.iter_mut() {
            if req.app_id == app_id && !req.fulfilled {
                req.fulfilled = true;
                self.preload_hit_count = self.preload_hit_count.saturating_add(1);
                return;
            }
        }
        // Not in preload queue -> miss (app launched without prediction)
        self.preload_miss_count = self.preload_miss_count.saturating_add(1);
    }

    /// Compute the preload hit rate as Q16
    pub fn preload_accuracy(&self) -> i32 {
        let total = self.preload_hit_count + self.preload_miss_count;
        if total == 0 {
            return Q16_HALF;
        }
        q16_div(self.preload_hit_count as i32, total as i32)
    }

    /// Optimize layout ordering based on usage scores
    pub fn optimize_layout(&mut self, scores: &[(u16, i32)]) {
        if !self.enabled {
            return;
        }

        // Update existing slot scores or create new ones
        for &(item_id, score) in scores {
            let mut found = false;
            for slot in self.layout_slots.iter_mut() {
                if slot.item_id == item_id {
                    if !slot.locked {
                        // Blend: 70% new score + 30% old score for stability
                        let blended = q16_mul(score, 45875)     // 0.7
                            + q16_mul(slot.adapted_score, 19661); // 0.3
                        if blended > slot.adapted_score {
                            slot.times_promoted = slot.times_promoted.saturating_add(1);
                        } else if blended < slot.adapted_score {
                            slot.times_demoted = slot.times_demoted.saturating_add(1);
                        }
                        slot.adapted_score = blended;
                    }
                    found = true;
                    break;
                }
            }
            if !found && self.layout_slots.len() < MAX_LAYOUT_ITEMS {
                self.layout_slots.push(LayoutSlot {
                    item_id,
                    base_position: self.layout_slots.len() as u8,
                    adapted_score: score,
                    times_promoted: 0,
                    times_demoted: 0,
                    locked: false,
                });
            }
        }

        // Sort by adapted_score descending (insertion sort for small N)
        let len = self.layout_slots.len();
        for i in 1..len {
            let mut j = i;
            while j > 0
                && self.layout_slots[j].adapted_score > self.layout_slots[j - 1].adapted_score
            {
                self.layout_slots.swap(j, j - 1);
                j -= 1;
            }
        }
    }

    /// Get the current layout ordering (item_ids in adapted order)
    pub fn get_layout_order(&self) -> Vec<u16> {
        self.layout_slots.iter().map(|s| s.item_id).collect()
    }

    /// Lock a layout slot so it won't be moved by adaptation
    pub fn lock_layout_slot(&mut self, item_id: u16) {
        for slot in self.layout_slots.iter_mut() {
            if slot.item_id == item_id {
                slot.locked = true;
                return;
            }
        }
    }

    /// Generate contextual suggestions
    pub fn generate_suggestions(
        &mut self,
        _hour: u8,
        _day: u8,
        app_predictions: &[(u16, i32)],
        sequence_predictions: &[(u16, u16, i32)],
    ) {
        if !self.enabled {
            return;
        }

        // Expire old suggestions
        self.suggestions
            .retain(|s| !s.dismissed && s.created_at + 120000 > self.current_tick);

        // Scale suggestion confidence by overall acceptance rate
        let accept_factor = q16_clamp01(self.suggestion_accept_rate);

        // Time-based app suggestions
        for &(app_id, raw_conf) in app_predictions {
            if self.suggestions.len() >= MAX_SUGGESTIONS {
                break;
            }
            let confidence = q16_mul(raw_conf, accept_factor);
            if confidence < Q16_THRESHOLD_LOW {
                continue;
            }

            let already = self
                .suggestions
                .iter()
                .any(|s| s.kind == SuggestionKind::LaunchApp && s.target_id == app_id as u32);
            if already {
                continue;
            }

            self.suggestions.push(AdaptiveSuggestion {
                kind: SuggestionKind::LaunchApp,
                target_id: app_id as u32,
                confidence,
                reason_code: 0x0001, // time-based pattern
                shown: false,
                accepted: false,
                dismissed: false,
                created_at: self.current_tick,
            });
        }

        // Sequence-based suggestions: "you just opened A, you usually open B next"
        for &(_first, second, seq_conf) in sequence_predictions {
            if self.suggestions.len() >= MAX_SUGGESTIONS {
                break;
            }
            let confidence = q16_mul(seq_conf, accept_factor);
            if confidence < Q16_THRESHOLD_LOW {
                continue;
            }

            let already = self
                .suggestions
                .iter()
                .any(|s| s.kind == SuggestionKind::RunShortcut && s.target_id == second as u32);
            if already {
                continue;
            }

            self.suggestions.push(AdaptiveSuggestion {
                kind: SuggestionKind::RunShortcut,
                target_id: second as u32,
                confidence,
                reason_code: 0x0002, // sequence pattern
                shown: false,
                accepted: false,
                dismissed: false,
                created_at: self.current_tick,
            });
        }
    }

    /// User accepted a suggestion
    pub fn accept_suggestion(&mut self, index: usize) {
        if index < self.suggestions.len() {
            self.suggestions[index].accepted = true;
            // Update acceptance rate: EMA with 0.1 weight for new observation
            self.suggestion_accept_rate = q16_mul(self.suggestion_accept_rate, 58982) // 0.9
                + Q16_TENTH; // +0.1 for success
            self.suggestion_accept_rate = q16_clamp01(self.suggestion_accept_rate);
        }
    }

    /// User dismissed a suggestion
    pub fn dismiss_suggestion(&mut self, index: usize) {
        if index < self.suggestions.len() {
            self.suggestions[index].dismissed = true;
            // Decrease acceptance rate
            self.suggestion_accept_rate = q16_mul(self.suggestion_accept_rate, 58982); // 0.9
            self.suggestion_accept_rate = q16_clamp01(self.suggestion_accept_rate);
        }
    }

    /// Generate resource allocation hints for predicted workloads
    pub fn generate_resource_hints(&mut self, predictions: &[(u16, i32)]) {
        if !self.enabled {
            return;
        }

        self.resource_hints
            .retain(|h| h.valid_until > self.current_tick);

        for &(app_id, confidence) in predictions {
            if self.resource_hints.len() >= MAX_RESOURCE_HINTS {
                break;
            }
            if confidence < Q16_QUARTER {
                continue;
            }

            let already = self.resource_hints.iter().any(|h| h.app_id == app_id);
            if already {
                continue;
            }

            // Scale resource priority by confidence
            let cpu_weight = q16_mul(confidence, Q16_HALF);
            let mem_priority = confidence;
            let io_priority = q16_mul(confidence, Q16_QUARTER);

            self.resource_hints.push(ResourceHint {
                app_id,
                cpu_weight: q16_clamp01(cpu_weight),
                memory_priority: q16_clamp01(mem_priority),
                io_priority: q16_clamp01(io_priority),
                valid_until: self.current_tick + 30000,
            });
        }
    }

    /// Check and emit habit nudges based on current time
    pub fn check_habit_nudges(&self, hour: u8, day: u8) -> Vec<u16> {
        let day_bit = 1u8 << (day % 7);
        let mut active_nudges = Vec::new();

        for nudge in &self.habit_nudges {
            if !nudge.active {
                continue;
            }
            if nudge.hour_trigger != hour {
                continue;
            }
            if nudge.day_mask & day_bit == 0 {
                continue;
            }
            if nudge.strength < Q16_THRESHOLD_LOW {
                continue;
            }

            active_nudges.push(nudge.habit_id);
        }

        active_nudges
    }

    /// Register a new habit nudge
    pub fn add_habit_nudge(
        &mut self,
        habit_id: u16,
        message_code: u16,
        strength: i32,
        hour: u8,
        day_mask: u8,
    ) {
        if self.habit_nudges.len() >= MAX_HABIT_NUDGES {
            return;
        }
        self.habit_nudges.push(HabitNudge {
            habit_id,
            message_code,
            strength: q16_clamp01(strength),
            hour_trigger: hour,
            day_mask,
            times_shown: 0,
            times_followed: 0,
            active: true,
        });
    }

    /// Record that a habit nudge was followed
    pub fn habit_followed(&mut self, habit_id: u16) {
        for nudge in self.habit_nudges.iter_mut() {
            if nudge.habit_id == habit_id {
                nudge.times_followed = nudge.times_followed.saturating_add(1);
                // Increase strength slightly as reward
                nudge.strength = q16_clamp01(nudge.strength + Q16_TENTH / 2);
                return;
            }
        }
    }

    /// Record that a habit nudge was ignored
    pub fn habit_ignored(&mut self, habit_id: u16) {
        for nudge in self.habit_nudges.iter_mut() {
            if nudge.habit_id == habit_id {
                nudge.times_shown = nudge.times_shown.saturating_add(1);
                // Decrease strength to avoid annoyance
                nudge.strength = q16_clamp01(nudge.strength - Q16_TENTH / 4);
                if nudge.strength < Q16_TENTH {
                    nudge.active = false; // too many ignores, disable
                }
                return;
            }
        }
    }

    /// Advance the tick counter
    pub fn tick(&mut self, now: u64) {
        self.current_tick = now;
    }
}

// ── Global state ───────────────────────────────────────────────────────────

static ADAPTATION: Mutex<Option<AdaptationEngine>> = Mutex::new(None);

pub fn init() {
    let mut guard = ADAPTATION.lock();
    *guard = Some(AdaptationEngine::new());
    serial_println!("    [learning] Adaptation engine initialized");
}

/// Update the current tick
pub fn tick(now: u64) {
    let mut guard = ADAPTATION.lock();
    if let Some(engine) = guard.as_mut() {
        engine.tick(now);
    }
}

/// Generate preload requests from predictions
pub fn preload(current_app: u16, hour: u8, day: u8, predictions: &[(u16, i32)]) {
    let mut guard = ADAPTATION.lock();
    if let Some(engine) = guard.as_mut() {
        engine.generate_preloads(current_app, hour, day, predictions);
    }
}

/// Report a preload hit (user opened a preloaded app)
pub fn preload_hit(app_id: u16) {
    let mut guard = ADAPTATION.lock();
    if let Some(engine) = guard.as_mut() {
        engine.preload_hit(app_id);
    }
}

/// Update layout based on scores
pub fn optimize_layout(scores: &[(u16, i32)]) {
    let mut guard = ADAPTATION.lock();
    if let Some(engine) = guard.as_mut() {
        engine.optimize_layout(scores);
    }
}

/// Get the adapted layout order
pub fn layout_order() -> Vec<u16> {
    let guard = ADAPTATION.lock();
    if let Some(engine) = guard.as_ref() {
        engine.get_layout_order()
    } else {
        Vec::new()
    }
}
