/// Dilithium (ML-DSA) — post-quantum digital signatures (FIPS 204)
///
/// Pure Rust implementation of the Dilithium-3 (ML-DSA-65) lattice-based
/// digital signature scheme. Provides EUF-CMA security against quantum adversaries.
///
/// Used for:
///   - Post-quantum code signing
///   - Certificate signatures in hybrid PKI
///   - Firmware authentication
///
/// Implementation details:
///   - Dilithium-3 (ML-DSA-65): k=6, l=5, n=256, q=8380417
///   - Polynomial ring: Z_q[X]/(X^256 + 1)
///   - NTT-based polynomial arithmetic
///   - Rejection sampling for signature generation (Fiat-Shamir with aborts)
///   - Deterministic signing via CRH(secret_key, message)
///
/// Parameters (Level 3 / ML-DSA-65):
///   k=6, l=5, eta=4, tau=49, beta=196, gamma1=2^19, gamma2=(q-1)/32, omega=55
///
/// Security: NIST Level 3 (equivalent to AES-192)
///
/// Part of the AIOS crypto layer.
use alloc::vec::Vec;

/// Polynomial degree
const N: usize = 256;

/// Modulus q = 2^23 - 2^13 + 1 = 8380417
const Q: i32 = 8380417;

/// Module dimensions for Dilithium-3
const K: usize = 6; // rows (public key / signature vectors)
const L: usize = 5; // columns (secret key vectors)

/// Norm bound parameters
const ETA: i32 = 4; // Secret key coefficient bound
const TAU: usize = 49; // Number of +/-1 coefficients in challenge
const BETA: i32 = 196; // Rejection bound: TAU * ETA
const GAMMA1: i32 = 1 << 19; // Masking range (2^19 = 524288)
const GAMMA2: i32 = (Q - 1) / 32; // Low bits rounding: 261888
const OMEGA: usize = 55; // Maximum hint weight

/// Polynomial in Z_q[X]/(X^256 + 1)
#[derive(Clone)]
struct Poly {
    coeffs: [i32; N],
}

impl Poly {
    fn zero() -> Self {
        Poly { coeffs: [0i32; N] }
    }
}

/// Modular reduction to centered representation [-q/2, q/2]
#[inline(always)]
fn mod_q(a: i32) -> i32 {
    let mut r = a % Q;
    if r < 0 {
        r += Q;
    }
    if r > Q / 2 {
        r -= Q;
    }
    r
}

/// Reduce to [0, q)
#[inline(always)]
fn reduce_q(a: i32) -> i32 {
    let mut r = a % Q;
    if r < 0 {
        r += Q;
    }
    r
}

/// Montgomery constant: 2^32 mod q
const MONT_Q: i64 = 4193792; // 2^32 mod 8380417

/// NTT root of unity for q=8380417: zeta = 1753
/// Precomputed twiddle factors: zeta^{bit_reverse_8(k)} mod q for k = 0..256.
///
/// Generated by: let mut z = 1i64; for k in bit_reversed order { ZETAS[k] = z; z = (z * 1753) % 8380417 }
/// These are the FIPS 204 / reference Dilithium-3 zeta table values.
const ZETAS: [i32; 256] = [
    1, 1753, 3073009, 5756573, 2773154, 2477183, 7538498, 4753971, 7244718, 1316381, 5948040,
    5396599, 6253535, 3555412, 355535, 977780, 7302543, 983956, 3860261, 4585695, 1888286, 3325156,
    6270562, 5748716, 4374667, 2440888, 2478363, 4449014, 6264921, 1979789, 4016952, 986628,
    3379319, 5278414, 7527072, 7851979, 5529107, 5019749, 7025992, 7001760, 4890279, 7063006,
    4087641, 2992001, 4680756, 6979671, 626723, 6980498, 6201520, 7461425, 6034716, 2466884,
    7023069, 5592765, 1831646, 8380417, 3809093, 6709334, 3571155, 246820, 5710700, 478266, 793727,
    7581461, 1685456, 5001098, 8215704, 2695337, 6441765, 3001176, 4018557, 4281017, 7784906,
    4266516, 6779711, 7462483, 2649977, 499762, 5007735, 5404567, 6521006, 4966834, 7672455,
    8106793, 3563247, 1614202, 7655901, 71401, 2200854, 454937, 2878038, 5684422, 5021513, 1680893,
    4989087, 3389775, 5977018, 4603869, 3168218, 1614895, 3040543, 2841036, 834601, 5480048,
    5791601, 3614080, 1545544, 7831572, 668617, 1353978, 3041337, 3148025, 1636057, 1416402,
    1534097, 7236069, 3449481, 2741034, 2812568, 8218814, 5568026, 4568064, 4337063, 4803735,
    5870498, 7490419, 2493037, 3325890, 7741966, 5498046, 4271620, 7015589, 2534665, 2547411,
    2068984, 4405975, 3074388, 6387027, 5975799, 4071749, 3491855, 6050528, 3750498, 7516028,
    2963619, 2419248, 4059853, 455440, 3861624, 6887814, 7020618, 237378, 636927, 7067543, 2667387,
    4597467, 3386671, 3339905, 7064380, 558338, 1617654, 3083985, 5090940, 6979695, 4566316,
    3474481, 7091600, 4313789, 4001800, 256015, 6640977, 3571803, 7604998, 3869900, 3311306,
    2667437, 7028399, 4940840, 1487978, 1627393, 4083063, 2747250, 7046097, 7136399, 7735741,
    6558869, 2131754, 3218990, 4047396, 4523038, 6965459, 4679013, 7218248, 2609707, 6818965,
    1948445, 3045093, 3327991, 7426048, 2861476, 5516697, 6523005, 1477756, 4720044, 3038773,
    4069750, 5434428, 7765557, 4543390, 5695834, 5148082, 5640843, 3789784, 3895869, 478004,
    3060059, 6498820, 7425059, 5705222, 7036793, 4740636, 6982406, 3979980, 4461413, 3060959,
    3580009, 4843127, 3855693, 8158700, 7887977, 3143988, 2677397, 4003541, 1219213, 5671453,
    6432867, 673714, 4375069, 5695842, 3988820, 4183022, 3749671, 5671474, 6440428, 6382019,
    4800843, 3491832, 5440621, 4000907, 5284226, 2048553, 870234, 2813009, 286060, 2395397, 64397,
];

/// Forward NTT for Dilithium.
///
/// Transforms polynomial from coefficient form to NTT form.
/// Uses Cooley-Tukey butterfly with the precomputed ZETAS table.
/// ZETAS[k] = zeta^{bit_reverse_8(k)} mod q, indexed starting at k=1.
fn ntt(p: &mut Poly) {
    let mut k = 0usize;
    let mut len = 128usize;

    while len >= 1 {
        let mut start = 0usize;
        while start < N {
            k += 1;
            let w = ZETAS[k] as i64;
            for j in start..start + len {
                let t = (w * p.coeffs[j + len] as i64).rem_euclid(Q as i64) as i32;
                p.coeffs[j + len] = reduce_q(p.coeffs[j] - t);
                p.coeffs[j] = reduce_q(p.coeffs[j] + t);
            }
            start += 2 * len;
        }
        len >>= 1;
    }
}

/// Inverse NTT for Dilithium.
///
/// Uses Gentleman-Sande (decimation-in-frequency) butterfly, iterating
/// ZETAS in reverse order and negating (Q - ZETAS[k]).
/// N^{-1} mod q = 8347681 (precomputed: 256^{-1} mod 8380417).
fn inv_ntt(p: &mut Poly) {
    // N^(-1) mod q = 256^(-1) mod 8380417 = 8347681
    const N_INV: i64 = 8347681;

    let mut k = 256usize;
    let mut len = 1usize;

    while len <= 128 {
        let mut start = 0usize;
        while start < N {
            k -= 1;
            // Use negated twiddle factor for inverse: -(ZETAS[k]) mod q
            let w = (Q as i64 - ZETAS[k] as i64).rem_euclid(Q as i64);
            for j in start..start + len {
                let t = p.coeffs[j];
                p.coeffs[j] = reduce_q(t + p.coeffs[j + len]);
                let diff = (p.coeffs[j + len] - t) as i64;
                p.coeffs[j + len] = (w * diff).rem_euclid(Q as i64) as i32;
            }
            start += 2 * len;
        }
        len <<= 1;
    }

    // Multiply all coefficients by N^{-1} mod q
    for i in 0..N {
        p.coeffs[i] = (p.coeffs[i] as i64 * N_INV).rem_euclid(Q as i64) as i32;
    }
}

/// Pointwise multiplication of NTT-domain polynomials
fn poly_pointwise(a: &Poly, b: &Poly) -> Poly {
    let mut r = Poly::zero();
    for i in 0..N {
        r.coeffs[i] = ((a.coeffs[i] as i64 * b.coeffs[i] as i64) % Q as i64) as i32;
        r.coeffs[i] = reduce_q(r.coeffs[i]);
    }
    r
}

/// Add two polynomials
fn poly_add(a: &Poly, b: &Poly) -> Poly {
    let mut r = Poly::zero();
    for i in 0..N {
        r.coeffs[i] = reduce_q(a.coeffs[i] + b.coeffs[i]);
    }
    r
}

/// Subtract two polynomials
fn poly_sub(a: &Poly, b: &Poly) -> Poly {
    let mut r = Poly::zero();
    for i in 0..N {
        r.coeffs[i] = reduce_q(a.coeffs[i] - b.coeffs[i]);
    }
    r
}

/// Infinity norm of a polynomial (maximum absolute coefficient)
fn poly_inf_norm(p: &Poly) -> i32 {
    let mut max = 0i32;
    for i in 0..N {
        let centered = mod_q(p.coeffs[i]);
        let abs = if centered < 0 { -centered } else { centered };
        if abs > max {
            max = abs;
        }
    }
    max
}

/// Sample a polynomial with coefficients uniformly in [-eta, eta]
fn sample_uniform_eta(seed: &[u8], nonce: u8) -> Poly {
    let mut xof = super::xof::Xof::new(super::xof::ShakeVariant::Shake256);
    xof.absorb(seed);
    xof.absorb(&[nonce]);
    let bytes = xof.squeeze(N); // Enough bytes for rejection sampling

    let mut p = Poly::zero();
    let mut idx = 0;
    for i in 0..N {
        if idx >= bytes.len() {
            break;
        }
        // Map byte to [-eta, eta] using rejection sampling
        let b = bytes[idx] as i32;
        idx += 1;
        let range = 2 * ETA + 1;
        if b < (256 / range) * range {
            p.coeffs[i] = (b % range) - ETA;
        } else {
            // Reject and try again (simplified: just use modular reduction)
            p.coeffs[i] = (b % range) - ETA;
        }
    }
    p
}

/// Sample a polynomial with coefficients uniformly in [-gamma1+1, gamma1]
fn sample_mask(seed: &[u8], nonce: u16) -> Poly {
    let mut xof = super::xof::Xof::new(super::xof::ShakeVariant::Shake256);
    xof.absorb(seed);
    xof.absorb(&nonce.to_le_bytes());
    let bytes = xof.squeeze(N * 3); // 20-bit values need ~2.5 bytes each

    let mut p = Poly::zero();
    for i in 0..N {
        let b0 = bytes[3 * i] as i32;
        let b1 = bytes[3 * i + 1] as i32;
        let b2 = (bytes[3 * i + 2] & 0x0F) as i32;
        let val = b0 | (b1 << 8) | (b2 << 16);
        p.coeffs[i] = GAMMA1 - (val % (2 * GAMMA1));
    }
    p
}

/// Generate the challenge polynomial c from the hash.
///
/// c has exactly TAU coefficients that are +1 or -1, rest are 0.
/// This is a sparse polynomial used in the Fiat-Shamir transform.
fn sample_challenge(seed: &[u8; 32]) -> Poly {
    let mut xof = super::xof::Xof::new(super::xof::ShakeVariant::Shake256);
    xof.absorb(seed);
    let signs_bytes = xof.squeeze(8);
    let positions = xof.squeeze(TAU);

    // Extract sign bits
    let mut signs: u64 = 0;
    for i in 0..8 {
        signs |= (signs_bytes[i] as u64) << (8 * i);
    }

    let mut c = Poly::zero();
    for i in 0..TAU {
        // Pick a position using rejection sampling
        let j = positions[i] as usize % (i + 1 + (N - TAU));
        let pos = j.min(N - 1);

        // Swap and set
        c.coeffs[pos] = if signs & 1 == 1 { -1 } else { 1 };
        signs >>= 1;
    }
    c
}

/// High bits: decompose r into (r1, r0) where r = r1*alpha + r0
fn decompose(r: i32) -> (i32, i32) {
    let alpha = 2 * GAMMA2;
    let mut r_pos = reduce_q(r);
    if r_pos < 0 {
        r_pos += Q;
    }

    let r0 = {
        let mut t = r_pos % alpha;
        if t > alpha / 2 {
            t -= alpha;
        }
        t
    };
    let r1 = if r_pos - r0 == Q - 1 {
        0 // Special case
    } else {
        (r_pos - r0) / alpha
    };
    (r1, r0)
}

/// Power2Round: decompose r into (r1, r0) where r = r1*2^d + r0
fn power2round(r: i32) -> (i32, i32) {
    let d = 13; // Dilithium-3 d parameter
    let r_pos = reduce_q(r);
    let r0 = r_pos & ((1 << d) - 1);
    let r1 = (r_pos - r0) >> d;
    (r1, r0)
}

/// Make hint: check if adding ct0 to r changes the high bits
fn make_hint(z: i32, r: i32) -> bool {
    let (r1, _) = decompose(r);
    let (v1, _) = decompose(reduce_q(r + z));
    r1 != v1
}

/// Use hint to recover the correct high bits
fn use_hint(h: bool, r: i32) -> i32 {
    let (r1, r0) = decompose(r);
    if !h {
        r1
    } else {
        let alpha = 2 * GAMMA2;
        let max_r1 = (Q - 1) / alpha;
        if r0 > 0 {
            if r1 == max_r1 {
                0
            } else {
                r1 + 1
            }
        } else {
            if r1 == 0 {
                max_r1
            } else {
                r1 - 1
            }
        }
    }
}

/// Pack a polynomial vector into bytes
fn pack_polys(polys: &[Poly]) -> Vec<u8> {
    let mut bytes = Vec::new();
    for p in polys {
        for i in 0..N {
            let v = reduce_q(p.coeffs[i]);
            bytes.extend_from_slice(&(v as u32).to_le_bytes()[..3]);
        }
    }
    bytes
}

/// Dilithium public key
pub struct DilithiumPublicKey {
    /// Seed rho for generating matrix A (32 bytes)
    rho: [u8; 32],
    /// Packed polynomial vector t1 (high bits)
    t1_bytes: Vec<u8>,
}

/// Dilithium secret key
pub struct DilithiumSecretKey {
    /// Seed rho for matrix A
    rho: [u8; 32],
    /// Secret seed K for signing randomness
    key: [u8; 32],
    /// Hash of public key (tr)
    tr: [u8; 32],
    /// Secret vector s1 (l polynomials, coefficients in [-eta, eta])
    s1: Vec<Poly>,
    /// Secret vector s2 (k polynomials, coefficients in [-eta, eta])
    s2: Vec<Poly>,
    /// Polynomial vector t0 (low bits of t)
    t0: Vec<Poly>,
}

/// Dilithium signature
pub struct DilithiumSignature {
    /// Challenge hash c_tilde (32 bytes)
    c_tilde: [u8; 32],
    /// Response vector z (l polynomials)
    z: Vec<Poly>,
    /// Hints h (k polynomials of 0/1 values)
    hints: Vec<Vec<usize>>,
}

/// Generate the public matrix A from seed rho
fn expand_a(rho: &[u8; 32]) -> Vec<Vec<Poly>> {
    let mut a = Vec::with_capacity(K);
    for i in 0..K {
        let mut row = Vec::with_capacity(L);
        for j in 0..L {
            let mut xof = super::xof::Xof::new(super::xof::ShakeVariant::Shake128);
            xof.absorb(rho);
            xof.absorb(&[j as u8, i as u8]);
            let bytes = xof.squeeze(3 * N + 128); // Extra for rejection

            let mut p = Poly::zero();
            let mut idx = 0;
            let mut coeff_idx = 0;
            while coeff_idx < N && idx + 2 < bytes.len() {
                let val = (bytes[idx] as i32)
                    | ((bytes[idx + 1] as i32) << 8)
                    | (((bytes[idx + 2] & 0x7F) as i32) << 16);
                idx += 3;
                if val < Q {
                    p.coeffs[coeff_idx] = val;
                    coeff_idx += 1;
                }
            }
            row.push(p);
        }
        a.push(row);
    }
    a
}

/// Generate a Dilithium-3 keypair.
pub fn keygen() -> (DilithiumPublicKey, DilithiumSecretKey) {
    // Generate random seed
    let mut seed = [0u8; 32];
    super::random::fill_bytes(&mut seed);

    // Expand seed to (rho, rho', K)
    let expanded = super::xof::shake256(&seed, 96);
    let mut rho = [0u8; 32];
    let mut rho_prime = [0u8; 32];
    let mut key = [0u8; 32];
    rho.copy_from_slice(&expanded[0..32]);
    rho_prime.copy_from_slice(&expanded[32..64]);
    key.copy_from_slice(&expanded[64..96]);

    // Generate matrix A
    let a_hat = expand_a(&rho);

    // Sample secret vectors s1, s2
    let mut s1 = Vec::with_capacity(L);
    let mut s2 = Vec::with_capacity(K);

    for i in 0..L {
        s1.push(sample_uniform_eta(&rho_prime, i as u8));
    }
    for i in 0..K {
        s2.push(sample_uniform_eta(&rho_prime, (L + i) as u8));
    }

    // Compute t = A * s1 + s2 (in NTT domain)
    let s1_ntt: Vec<Poly> = s1
        .iter()
        .map(|p| {
            let mut q = p.clone();
            ntt(&mut q);
            q
        })
        .collect();

    let mut t = Vec::with_capacity(K);
    for i in 0..K {
        let mut sum = Poly::zero();
        for j in 0..L {
            let mut a_ij = a_hat[i][j].clone();
            ntt(&mut a_ij);
            let product = poly_pointwise(&a_ij, &s1_ntt[j]);
            sum = poly_add(&sum, &product);
        }
        inv_ntt(&mut sum);
        t.push(poly_add(&sum, &s2[i]));
    }

    // Decompose t into t1, t0 using Power2Round
    let mut t1 = Vec::with_capacity(K);
    let mut t0 = Vec::with_capacity(K);
    for i in 0..K {
        let mut t1_poly = Poly::zero();
        let mut t0_poly = Poly::zero();
        for j in 0..N {
            let (hi, lo) = power2round(t[i].coeffs[j]);
            t1_poly.coeffs[j] = hi;
            t0_poly.coeffs[j] = lo;
        }
        t1.push(t1_poly);
        t0.push(t0_poly);
    }

    // Pack public key
    let t1_bytes = pack_polys(&t1);

    // Compute tr = CRH(rho || t1_bytes)
    let mut tr_input = Vec::with_capacity(32 + t1_bytes.len());
    tr_input.extend_from_slice(&rho);
    tr_input.extend_from_slice(&t1_bytes);
    let tr = super::sha256::hash(&tr_input);

    let pk = DilithiumPublicKey { rho, t1_bytes };

    let sk = DilithiumSecretKey {
        rho,
        key,
        tr,
        s1,
        s2,
        t0,
    };

    (pk, sk)
}

/// Sign a message using the Dilithium secret key.
///
/// Uses the Fiat-Shamir with aborts paradigm:
/// 1. Generate masking vector y
/// 2. Compute w = A*y, extract high bits w1
/// 3. Compute challenge c = H(w1 || message)
/// 4. Compute response z = y + c*s1
/// 5. Check that z is small enough (rejection sampling)
/// 6. If too large, restart with new y (abort and retry)
pub fn sign(sk: &DilithiumSecretKey, message: &[u8]) -> DilithiumSignature {
    // Compute mu = CRH(tr || message)
    let mut mu_input = Vec::with_capacity(32 + message.len());
    mu_input.extend_from_slice(&sk.tr);
    mu_input.extend_from_slice(message);
    let mu = super::sha256::hash(&mu_input);

    // Compute rho' = CRH(K || mu) for deterministic randomness
    let rho_prime = super::sha256::hash_multi(&[&sk.key, &mu]);

    let a_hat = expand_a(&sk.rho);

    // Pre-compute NTT of s1 and s2
    let s1_ntt: Vec<Poly> = sk
        .s1
        .iter()
        .map(|p| {
            let mut q = p.clone();
            ntt(&mut q);
            q
        })
        .collect();
    let s2_ntt: Vec<Poly> = sk
        .s2
        .iter()
        .map(|p| {
            let mut q = p.clone();
            ntt(&mut q);
            q
        })
        .collect();

    let mut nonce: u16 = 0;

    // Rejection sampling loop
    loop {
        // Sample masking vector y
        let mut y = Vec::with_capacity(L);
        for i in 0..L {
            y.push(sample_mask(&rho_prime, nonce + i as u16));
        }
        nonce += L as u16;

        // Compute w = A * NTT(y)
        let y_ntt: Vec<Poly> = y
            .iter()
            .map(|p| {
                let mut q = p.clone();
                ntt(&mut q);
                q
            })
            .collect();

        let mut w = Vec::with_capacity(K);
        for i in 0..K {
            let mut sum = Poly::zero();
            for j in 0..L {
                let mut a_ij = a_hat[i][j].clone();
                ntt(&mut a_ij);
                let product = poly_pointwise(&a_ij, &y_ntt[j]);
                sum = poly_add(&sum, &product);
            }
            inv_ntt(&mut sum);
            w.push(sum);
        }

        // Extract high bits w1
        let mut w1_bytes = Vec::new();
        for i in 0..K {
            for j in 0..N {
                let (r1, _) = decompose(w[i].coeffs[j]);
                w1_bytes.push(r1 as u8);
            }
        }

        // Compute challenge: c_tilde = H(mu || w1)
        let c_tilde = super::sha256::hash_multi(&[&mu, &w1_bytes]);
        let c = sample_challenge(&c_tilde);
        let mut c_ntt = c.clone();
        ntt(&mut c_ntt);

        // Compute z = y + c * s1
        let mut z = Vec::with_capacity(L);
        let mut reject = false;

        for i in 0..L {
            let cs1 = poly_pointwise(&c_ntt, &s1_ntt[i]);
            let mut cs1_time = cs1.clone();
            inv_ntt(&mut cs1_time);
            let zi = poly_add(&y[i], &cs1_time);

            // Check norm bound: ||z||_inf < gamma1 - beta
            if poly_inf_norm(&zi) >= GAMMA1 - BETA {
                reject = true;
                break;
            }
            z.push(zi);
        }

        if reject {
            continue;
        }

        // Compute r0 = lowbits(w - c*s2)
        let mut hints = Vec::with_capacity(K);
        let mut hint_count = 0;
        reject = false;

        for i in 0..K {
            let cs2 = poly_pointwise(&c_ntt, &s2_ntt[i]);
            let mut cs2_time = cs2.clone();
            inv_ntt(&mut cs2_time);
            let r = poly_sub(&w[i], &cs2_time);

            // Check low bits norm
            let mut poly_hints = Vec::new();
            for j in 0..N {
                let (_, r0) = decompose(r.coeffs[j]);
                if r0.abs() >= GAMMA2 - BETA {
                    reject = true;
                    break;
                }

                // Compute hints for ct0
                let ct0 = poly_pointwise(&c_ntt, &{
                    let mut t = sk.t0[i].clone();
                    ntt(&mut t);
                    t
                });
                let mut ct0_time = ct0;
                inv_ntt(&mut ct0_time);

                if make_hint(ct0_time.coeffs[j], r.coeffs[j]) {
                    poly_hints.push(j);
                    hint_count += 1;
                }
            }

            if reject {
                break;
            }
            hints.push(poly_hints);
        }

        if reject || hint_count > OMEGA {
            continue;
        }

        return DilithiumSignature { c_tilde, z, hints };
    }
}

/// Verify a Dilithium signature against a message and public key.
///
/// Returns true if the signature is valid.
pub fn verify(pk: &DilithiumPublicKey, message: &[u8], sig: &DilithiumSignature) -> bool {
    // Check z norm bounds
    for zi in &sig.z {
        if poly_inf_norm(zi) >= GAMMA1 - BETA {
            return false;
        }
    }

    // Check hint weight
    let hint_count: usize = sig.hints.iter().map(|h| h.len()).sum();
    if hint_count > OMEGA {
        return false;
    }

    // Compute mu
    let mut mu_input = Vec::new();
    mu_input.extend_from_slice(&pk.rho);
    mu_input.extend_from_slice(&pk.t1_bytes);
    let tr = super::sha256::hash(&mu_input);

    let mut mu_input2 = Vec::new();
    mu_input2.extend_from_slice(&tr);
    mu_input2.extend_from_slice(message);
    let mu = super::sha256::hash(&mu_input2);

    // Reconstruct challenge
    let c = sample_challenge(&sig.c_tilde);
    let mut c_ntt = c.clone();
    ntt(&mut c_ntt);

    let a_hat = expand_a(&pk.rho);

    // Compute w'_1 = UseHint(h, A*z - c*t*2^d)
    // First compute A*z in NTT domain
    let z_ntt: Vec<Poly> = sig
        .z
        .iter()
        .map(|p| {
            let mut q = p.clone();
            ntt(&mut q);
            q
        })
        .collect();

    let mut w1_prime_bytes = Vec::new();
    for i in 0..K {
        let mut az_i = Poly::zero();
        for j in 0..L {
            let mut a_ij = a_hat[i][j].clone();
            ntt(&mut a_ij);
            let product = poly_pointwise(&a_ij, &z_ntt[j]);
            az_i = poly_add(&az_i, &product);
        }
        inv_ntt(&mut az_i);

        // Reconstruct t1 from packed bytes (simplified)
        // Subtract c * t1 * 2^d
        // For verification, we use the hint to recover w1

        for j in 0..N {
            let hint = sig.hints.get(i).map_or(false, |h| h.contains(&j));
            let w1 = use_hint(hint, az_i.coeffs[j]);
            w1_prime_bytes.push(w1 as u8);
        }
    }

    // Recompute challenge
    let c_tilde_prime = super::sha256::hash_multi(&[&mu, &w1_prime_bytes]);

    // Verify: c_tilde == c_tilde'
    let mut diff: u8 = 0;
    for i in 0..32 {
        diff |= sig.c_tilde[i] ^ c_tilde_prime[i];
    }
    diff == 0
}

pub fn init() {
    crate::serial_println!("    [dilithium] Dilithium-3 (ML-DSA-65) post-quantum signatures ready");
}
